version: "3"

services:
  blog:
    image: m1k1o/blog:latest
    restart: unless-stopped
    environment:
        TZ: Europe/Vienna
        BLOG_TITLE: Blog
        BLOG_NAME: Max Musermann
        BLOG_NICK: username
        BLOG_PASS: password
        BLOG_LANG: en
    ports:
      - 80:80
    volumes:
      - ./data:/var/www/html/data
